export const organDict = Object.fromEntries(
  Object.entries({
    breast: 'female',
    thymus: 'lymph',
    tonsil: 'tongue',
    ovary: 'female',
    'thyroid gland': 'thyroid',
    cervix: 'female',
    'seminal vesicle': 'male',
    endometrium: 'female',
    'fallopian tube': 'female',
    'adipose tissue': 'muscle',
    lung: 'lung',
    liver: 'liver',
    gallbladder: 'gallbladder',
    'smooth muscle': 'muscle',
    duodenum: 'small intestine',
    colon: 'colon',
    stomach: 'stomach',
    'adrenal gland': 'bladder',
    'small intestine': 'small intestine',
    rectum: 'colon',
    pancreas: 'pancreas',
    'choroid plexus': 'brain',
    'skeletal muscle': 'muscle',
    'salivary gland': 'tongue',
    spleen: 'spleen',
    'lymph node': 'lymph',
    appendix: 'colon',
    'bone marrow': 'bone',
    tongue: 'tongue',
    skin: 'muscle',
    testis: 'male',
    placenta: 'female',
    'parathyroid gland': 'thyroid',
    kidney: 'bladder',
    'heart muscle': 'heart',
    esophagus: 'muscle',
    epididymis: 'male',
    'cerebral cortex': 'brain',
    prostate: 'male',
    'urinary bladder': 'bladder',
  }).sort(([keyA], [keyB]) => keyA.localeCompare(keyB)),
);
